export const TOWER_TYPES = {
  shooter: {
    id: 'shooter',
    name: 'Shooter',
    cost: 30,
    range: 3,
    damage: 20,
    cooldown: 800,
    color: '#8B6914',
    desc: 'Single target damage',
    projectileColor: '#ffd700',
    projectileSpeed: 8,
  },
  slow: {
    id: 'slow',
    name: 'Freezer',
    cost: 40,
    range: 2.5,
    damage: 5,
    cooldown: 1200,
    slowFactor: 0.4,
    slowDuration: 2000,
    color: '#4a90d9',
    desc: 'Slows enemies',
    projectileColor: '#88ccff',
    projectileSpeed: 6,
  },
  splash: {
    id: 'splash',
    name: 'Splash',
    cost: 60,
    range: 2.5,
    damage: 30,
    splashRadius: 1.5,
    cooldown: 1500,
    color: '#cc4422',
    desc: 'Area damage',
    projectileColor: '#ff6644',
    projectileSpeed: 5,
  },
  money: {
    id: 'money',
    name: 'Miner',
    cost: 75,
    range: 0,
    damage: 0,
    cooldown: 0,
    color: '#ffd700',
    desc: '+8 gold / 5s',
  },
  water: {
    id: 'water',
    name: 'Water Wombat',
    cost: 50,
    range: 3.5,
    damage: 25,
    cooldown: 1000,
    color: '#2299cc',
    desc: 'Water only! Long range.',
    projectileColor: '#44ddff',
    projectileSpeed: 7,
    waterOnly: true,
  },
};

export function createTower(typeId, col, row) {
  const def = TOWER_TYPES[typeId];
  return {
    id: `tower-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    typeId,
    col,
    row,
    lastFired: 0,
    lastGold: 0,
    ...def,
  };
}
