export const TOWER_TYPES = {
  shooter: {
    id: 'shooter',
    name: 'Shooter',
    cost: 30,
    range: 3,
    damage: 20,
    cooldown: 800,
    color: '#8B6914',
    accent: '#c4952a',
    desc: 'Single target damage',
    projectileColor: '#ffd700',
    projectileSpeed: 8,
  },
  slow: {
    id: 'slow',
    name: 'Freezer',
    cost: 40,
    range: 2.5,
    damage: 5,
    cooldown: 1200,
    slowFactor: 0.4,
    slowDuration: 2000,
    color: '#4a90d9',
    accent: '#88ccff',
    desc: 'Slows enemies',
    projectileColor: '#88ccff',
    projectileSpeed: 6,
  },
  splash: {
    id: 'splash',
    name: 'Splash',
    cost: 60,
    range: 2.5,
    damage: 30,
    splashRadius: 1.5,
    cooldown: 1500,
    color: '#cc4422',
    accent: '#ff8844',
    desc: 'Area damage',
    projectileColor: '#ff6644',
    projectileSpeed: 5,
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    cost: 80,
    range: 6,
    damage: 80,
    cooldown: 2500,
    color: '#556677',
    accent: '#8899aa',
    desc: 'Extreme range, heavy hit',
    projectileColor: '#ffffff',
    projectileSpeed: 14,
  },
  chain: {
    id: 'chain',
    name: 'Chain Zapper',
    cost: 70,
    range: 2.5,
    damage: 15,
    cooldown: 1000,
    chainCount: 3,
    chainRange: 2,
    chainDecay: 0.7,
    color: '#9944cc',
    accent: '#cc88ff',
    desc: 'Lightning chains to 3 enemies',
    projectileColor: '#cc88ff',
    projectileSpeed: 12,
  },
  poison: {
    id: 'poison',
    name: 'Toxic',
    cost: 55,
    range: 2.5,
    damage: 8,
    cooldown: 900,
    poisonDps: 10,
    poisonDuration: 3000,
    color: '#44aa22',
    accent: '#88dd44',
    desc: 'Poison: 10 dmg/s for 3s',
    projectileColor: '#88dd44',
    projectileSpeed: 7,
  },
  money: {
    id: 'money',
    name: 'Miner',
    cost: 75,
    range: 0,
    damage: 0,
    cooldown: 0,
    color: '#ffd700',
    accent: '#ffee88',
    desc: '+8 gold / 5s',
  },
  water: {
    id: 'water',
    name: 'Water Wombat',
    cost: 50,
    range: 3.5,
    damage: 25,
    cooldown: 1000,
    color: '#2299cc',
    accent: '#44ddff',
    desc: 'Water only! Long range.',
    projectileColor: '#44ddff',
    projectileSpeed: 7,
    waterOnly: true,
  },
};

export function createTower(typeId, col, row) {
  const def = TOWER_TYPES[typeId];
  return {
    id: `tower-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    typeId,
    col,
    row,
    lastFired: 0,
    lastGold: 0,
    ...def,
  };
}
